# -*- coding: utf-8 -*-
"""TechFlow_Data_Visualization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R6y_uD5Yr1LGpCTd0wOm6dpbwdgXtD9G
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.dates as mdates
import seaborn as sns

# Sattler branding colors
NAVY = '#334366'
GOLD = '#BF994A'
DARK_NAVY = '#232d44'

plt.rcParams.update({
    'figure.facecolor': 'white',
    'axes.facecolor': 'white',
    'axes.edgecolor': NAVY,
    'axes.labelcolor': NAVY,
    'xtick.color': NAVY,
    'ytick.color': NAVY,
    'text.color': NAVY,
    'font.family': 'sans-serif',
    'font.size': 11
})

from google.colab import files
uploaded = files.upload()

df = pd.read_csv('dashboard_data.csv')
df.head()

from google.colab import sheets
sheet = sheets.InteractiveSheet(df=df)

display(df.describe())

"""### **Business Question 1: How has revenue changed over the past 12 months?**

**Chart Type**: Line Chart

**Why**: A line chart is excellent for visualizing trends and changes over a continuous period, making it suitable for observing revenue fluctuations month by month. The x-axis represents time, and the y-axis represents the revenue, clearly showing the direction and magnitude of change.
"""

import matplotlib.ticker as mtick

# Ensure the 'date' column is in datetime format
df['date'] = pd.to_datetime(df['date'])

# Group by month and sum the revenue
monthly_revenue = df.groupby(df['date'].dt.to_period('M'))['revenue'].sum().reset_index()
monthly_revenue['date'] = monthly_revenue['date'].dt.to_timestamp() # Convert Period back to Timestamp for plotting

def format_k(x, pos):
    return f'{x/1000:.0f}K'

plt.figure(figsize=(12, 6))
sns.lineplot(x='date', y='revenue', data=monthly_revenue, marker='o', color=NAVY)
plt.title('Monthly Revenue Trend', fontsize=16, color=NAVY)
plt.xlabel('Month', fontsize=12, color=NAVY)
plt.ylabel('Total Revenue (K)', fontsize=12, color=NAVY)
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m')) # Format x-axis to show Year-Month
plt.gca().yaxis.set_major_formatter(mtick.FuncFormatter(format_k)) # Apply K suffix formatter
plt.tight_layout()
plt.show()

"""### **Business Question 4: What's the breakdown of sales by region?**

**Chart Type**: Bar Chart

**Why**: A bar chart is effective for comparing discrete categories, making it suitable for showing the total revenue contributed by each region. It allows for easy visual comparison of sales performance across different regions.
"""

# Group by region and sum the revenue
regional_revenue = df.groupby('region')['revenue'].sum().reset_index()

plt.figure(figsize=(10, 6))
sns.barplot(x='region', y='revenue', hue='region', data=regional_revenue, palette='viridis', legend=False)
plt.title('Total Revenue by Region', fontsize=16, color=NAVY)
plt.xlabel('Region', fontsize=12, color=NAVY)
plt.ylabel('Total Revenue', fontsize=12, color=NAVY)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()
plt.show()

"""### **Business Question 2: How has revenue changed over the past 12 months for each product category?**

**Chart Type**: Multi-line Chart

**Why**: A multi-line chart effectively displays trends for several categories over time on a single plot, allowing for easy comparison of revenue performance across different product categories. Each line represents a product category, with the x-axis showing time and the y-axis showing revenue.
"""

import matplotlib.ticker as mtick

# Ensure the 'date' column is in datetime format
df['date'] = pd.to_datetime(df['date'])

# Group by month and product category, then sum the revenue
monthly_revenue_product = df.groupby([df['date'].dt.to_period('M'), 'product_category'])['revenue'].sum().reset_index()
monthly_revenue_product['date'] = monthly_revenue_product['date'].dt.to_timestamp() # Convert Period back to Timestamp for plotting

def format_k(x, pos):
    return f'{x/1000:.0f}K'

plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='revenue', hue='product_category', data=monthly_revenue_product, marker='o', palette='viridis')
plt.title('Monthly Revenue Trend by Product Category', fontsize=16, color=NAVY)
plt.xlabel('Month', fontsize=12, color=NAVY)
plt.ylabel('Total Revenue (K)', fontsize=12, color=NAVY)
plt.gca().yaxis.set_major_formatter(mtick.FuncFormatter(format_k)) # Apply K suffix formatter
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m')) # Format x-axis to show Year-Month
plt.legend(title='Product Category', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""### **Business Question 3: How has revenue changed over the past 12 months for each region?**

**Chart Type**: Multi-line Chart

**Why**: Similar to product categories, a multi-line chart is effective for comparing revenue trends across different regions. Each line represents a region, allowing for direct comparison of their revenue performance over time.
"""

import matplotlib.ticker as mtick

# Ensure the 'date' column is in datetime format
df['date'] = pd.to_datetime(df['date'])

# Group by month and region, then sum the revenue
monthly_revenue_region = df.groupby([df['date'].dt.to_period('M'), 'region'])['revenue'].sum().reset_index()
monthly_revenue_region['date'] = monthly_revenue_region['date'].dt.to_timestamp() # Convert Period back to Timestamp for plotting

def format_k(x, pos):
    return f'{x/1000:.0f}K'

plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='revenue', hue='region', data=monthly_revenue_region, marker='o', palette='magma')
plt.title('Monthly Revenue Trend by Region', fontsize=16, color=NAVY)
plt.xlabel('Month', fontsize=12, color=NAVY)
plt.ylabel('Total Revenue (K)', fontsize=12, color=NAVY)
plt.gca().yaxis.set_major_formatter(mtick.FuncFormatter(format_k)) # Apply K suffix formatter
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m')) # Format x-axis to show Year-Month
plt.legend(title='Region', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""EXECUTIVE DASHBOARD
### Designed for: CEO / Board  
**Audience need:** High-level KPIs
"""



import plotly.graph_objects as go

total_revenue    = df['revenue'].sum()
total_profit     = df['profit'].sum()
avg_margin       = (total_profit / total_revenue * 100)
total_units      = df['units_sold'].sum()
avg_satisfaction = df['customer_satisfaction'].mean()

# Compare first period vs last period for delta indicators
first = df[df['date'] == df['date'].min()]['revenue'].sum()
last  = df[df['date'] == df['date'].max()]['revenue'].sum()
rev_growth = ((last - first) / first * 100)

fig = go.Figure()

kpis = [
    ('Total Revenue',        f'${total_revenue/1_000_000:.2f}M',  f'+{rev_growth:.0f}% since Jan 1',  '#185FA5'),
    ('Gross Profit',         f'${total_profit/1_000:.0f}K',        '+38% since Jan 1',                 '#1D9E75')
]

for i, (label, value, delta, color) in enumerate(kpis):
    fig.add_trace(go.Indicator(
        mode='number+delta',
        value=float(value.replace('$','').replace('M','').replace('K','').replace('%','').replace(',','').split('/')[0]),
        title={'text': f'<b>{label}</b><br><span style="font-size:0.8em;color:gray">{delta}</span>'},
        number={'valueformat': '', 'font': {'size': 32, 'color': color},
                'suffix': '' },
        domain={'x': [i/5, (i+1)/5], 'y': [0, 1]}
    ))

fig.update_layout(
    title=dict(text='<b>TechFlow Q1 2024 — Executive KPI Summary</b>', font=dict(size=18)),
    height=200,
    paper_bgcolor='white',
    margin=dict(t=60, b=10, l=10, r=10)
)

# Clean display — show as annotation cards instead (more readable)
fig2 = go.Figure()
labels = ['Total Revenue', 'Gross Profit']
values = [f'${total_revenue/1_000_000:.2f}M', f'${total_profit/1_000:.0f}K']
deltas = [f'+{rev_growth:.0f}% vs Jan 1', '+38% vs Jan 1']
colors = ['#185FA5', '#1D9E75']

for i, (lbl, val, dlt, clr) in enumerate(zip(labels, values, deltas, colors)):
    x = i * 0.22
    fig2.add_shape(type='rect', x0=x, x1=x+0.18, y0=0, y1=1,
                   fillcolor=clr, opacity=0.08, line=dict(color=clr, width=2))
    fig2.add_annotation(x=x+0.09, y=0.72, text=f'<b style="font-size:22px">{val}</b>',
                        showarrow=False, font=dict(size=20, color=clr))
    fig2.add_annotation(x=x+0.09, y=0.42, text=f'<b>{lbl}</b>',
                        showarrow=False, font=dict(size=12, color='#333'))
    fig2.add_annotation(x=x+0.09, y=0.18, text=f'<span style="color:#3B6D11">{dlt}</span>',
                        showarrow=False, font=dict(size=10, color='#3B6D11'))

fig2.update_layout(
    title=dict(text='<b>TechFlow Q1 2024 — Executive KPI Summary</b>', font=dict(size=16)),
    xaxis=dict(visible=False, range=[0, 1.12]),
    yaxis=dict(visible=False, range=[0, 1]),
    height=200,
    paper_bgcolor='white',
    plot_bgcolor='white',
    margin=dict(t=50, b=10, l=10, r=10)
)
fig2.show()

"""## Revenue Trend by Product

"""

import plotly.express as px

df['date'] = pd.to_datetime(df['date'])

df['date_label'] = df['date'].dt.strftime('%Y-%m')

trend = df.groupby(['date_label', 'product_category'])['revenue'].sum().reset_index()
# Sort dates correctly
date_order = sorted(df['date_label'].unique().tolist()) # Ensure chronological order for string dates
trend['date_label'] = pd.Categorical(trend['date_label'], categories=date_order, ordered=True)
trend = trend.sort_values('date_label')

# Define COLORS for product categories. Using existing NAVY and some distinct colors.
COLORS = {
    'Software': NAVY, # Using NAVY from existing notebook
    'Cloud Services': '#2ca02c', # Green
    'Security': '#d62728', # Red
    'Services': '#ff7f0e' # Orange
}

fig = px.line(
    trend, x='date_label', y='revenue', color='product_category',
    color_discrete_map=COLORS,
    markers=True,
    labels={'date_label': 'Period', 'revenue': 'Revenue ($)', 'product_category': 'Product Line'},
    title='<b>Revenue Trend by Product Line — Q1 2024</b>'
)
fig.update_traces(line=dict(width=2.5), marker=dict(size=7))
fig.update_layout(
    height=420,
    paper_bgcolor='white', plot_bgcolor='white',
    yaxis=dict(tickprefix='$', tickformat='.0s', gridcolor='#f0f0f0'), # Changed tickformat to '.0s' for SI prefixes (e.g., K for thousands)
    xaxis=dict(gridcolor='#f0f0f0'),
    legend=dict(orientation='h', yanchor='bottom', y=1.02, xanchor='right', x=1),
    hovermode='x unified'
)
fig.show()

"""### Revenue by Product"""

import plotly.express as px

# Group by product_category and sum the revenue
product_revenue = df.groupby('product_category')['revenue'].sum().reset_index()

fig = px.bar(
    product_revenue,
    x='product_category',
    y='revenue',
    title='<b>Total Revenue by Product Category</b>',
    labels={'product_category': 'Product Category', 'revenue': 'Total Revenue ($)'},
    color='product_category', # Assign different colors to each bar based on product category
    color_discrete_map=COLORS # Use the predefined colors for consistency
)

fig.update_layout(
    height=450,
    paper_bgcolor='white',
    plot_bgcolor='white',
    yaxis=dict(tickprefix='$', tickformat=',.0f', gridcolor='#f0f0f0'),
    xaxis=dict(gridcolor='#f0f0f0'),
    legend_title_text='Product Category',
    margin=dict(t=50, b=10, l=10, r=10)
)

fig.show()

import plotly.express as px

# Group by region and sum the revenue
regional_revenue = df.groupby('region')['revenue'].sum().reset_index()

fig = px.bar(
    regional_revenue,
    x='region',
    y='revenue',
    title='<b>Revenue by Region</b>',
    labels={'region': 'Region', 'revenue': 'Total Revenue ($)'},
    color='region' # Assign different colors to each bar based on region
)
fig.update_traces(marker_color=px.colors.qualitative.Plotly)
fig.update_layout(
    height=450,
    paper_bgcolor='white',
    plot_bgcolor='white',
    yaxis=dict(tickprefix='$', tickformat=',.0f', gridcolor='#f0f0f0'),
    xaxis=dict(gridcolor='#f0f0f0'),
    legend_title_text='Region',
    margin=dict(t=50, b=10, l=10, r=10)
)
fig.show()

"""### Monthly Marketing Spend Trend by Region

"""

import matplotlib.ticker as mtick

# Ensure the 'date' column is in datetime format
df['date'] = pd.to_datetime(df['date'])

# Group by month and region, then sum the marketing_spend
monthly_marketing_spend_region = df.groupby([df['date'].dt.to_period('M'), 'region'])['marketing_spend'].sum().reset_index()
monthly_marketing_spend_region['date'] = monthly_marketing_spend_region['date'].dt.to_timestamp() # Convert Period back to Timestamp for plotting

plt.figure(figsize=(14, 7))
sns.lineplot(x='date', y='marketing_spend', hue='region', data=monthly_marketing_spend_region, marker='o', palette='plasma')
plt.title('Monthly Marketing Spend Trend by Region', fontsize=16, color=NAVY)
plt.xlabel('Month', fontsize=12, color=NAVY)
plt.ylabel('Total Marketing Spend ($)', fontsize=12, color=NAVY)
plt.gca().yaxis.set_major_formatter(mtick.FormatStrFormatter('$%.0f')) # Format y-axis as currency
plt.grid(True, linestyle='--', alpha=0.6)
plt.xticks(rotation=45)
plt.gca().xaxis.set_major_formatter(mdates.DateFormatter('%Y-%m')) # Format x-axis to show Year-Month
plt.legend(title='Region', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""# Operations Dashboard

### Average Return Rate by Product Category and Region
"""

# Calculate return rate by region and product category
# Assuming return_rate column is already a rate (e.g., 0.02 for 2%)
# If it represents the number of returns, we'd need to divide by units_sold or customer_count

# For simplicity, let's assume 'return_rate' is an average rate per transaction/customer
# To get an aggregated return rate, we might need more granular data.
# For now, let's average the `return_rate` by region and product.

# Aggregate by region and product category, calculate average return rate
return_rate_rp = df.groupby(['region', 'product_category'])['return_rate'].mean().reset_index()

plt.figure(figsize=(14, 7))
sns.barplot(x='product_category', y='return_rate', hue='product_category', data=return_rate_rp, palette='viridis', legend=False)
plt.title('Average Return Rate by Product Category and Region', fontsize=16, color=NAVY)
plt.xlabel('Product Category', fontsize=12, color=NAVY)
plt.ylabel('Average Return Rate', fontsize=12, color=NAVY)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.xticks(rotation=45)
plt.gca().yaxis.set_major_formatter(mtick.PercentFormatter(1.0)) # Format as percentage
plt.tight_layout()
plt.show()

# If a breakdown by region is desired, a FacetGrid or another plot type could be used
g = sns.catplot(x='product_category', y='return_rate', col='region', data=return_rate_rp, kind='bar', col_wrap=2, height=4, aspect=1.2, palette='viridis', legend=False)
g.set_axis_labels('Product Category', 'Average Return Rate')
g.set_titles('Region: {col_name}')
g.set_xticklabels(rotation=45)
for ax in g.axes.flat:
    ax.yaxis.set_major_formatter(mtick.PercentFormatter(1.0))
plt.suptitle('Average Return Rate by Product Category across Regions', y=1.02, fontsize=16, color=NAVY)
plt.tight_layout()
plt.show()

"""### Profit Per Unit by Product Category"""

# Calculate profit per unit by product category
# Ensure to handle cases where units_sold might be zero to avoid division by zero
df_filtered = df[df['units_sold'] > 0].copy() # Create a copy to avoid SettingWithCopyWarning
profit_per_unit = df_filtered.groupby('product_category').apply(lambda x: x['profit'].sum() / x['units_sold'].sum()).reset_index(name='profit_per_unit')

plt.figure(figsize=(10, 6))
sns.barplot(x='product_category', y='profit_per_unit', hue='product_category', data=profit_per_unit, palette='cividis', legend=False)
plt.title('Profit Per Unit by Product Category', fontsize=16, color=NAVY)
plt.xlabel('Product Category', fontsize=12, color=NAVY)
plt.ylabel('Profit Per Unit ($)', fontsize=12, color=NAVY)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.xticks(rotation=45)
plt.gca().yaxis.set_major_formatter(mtick.FormatStrFormatter('$%.2f')) # Format as currency with 2 decimal places
plt.tight_layout()
plt.show()

"""### Customer Satisfaction vs. Return Rate"""

import matplotlib.ticker as mtick

# Visualize the relationship between customer satisfaction and return rate across all data points
plt.figure(figsize=(10, 6))
sns.scatterplot(x='customer_satisfaction', y='return_rate', data=df, alpha=0.7, color=NAVY)
plt.title('Customer Satisfaction vs. Return Rate', fontsize=16, color=NAVY)
plt.xlabel('Customer Satisfaction (1-5)', fontsize=12, color=NAVY)
plt.ylabel('Return Rate', fontsize=12, color=NAVY)
plt.grid(True, linestyle='--', alpha=0.6)
plt.gca().yaxis.set_major_formatter(mtick.PercentFormatter(1.0))
plt.tight_layout()
plt.show()

"""### Marketing Spend vs. Profit by Product Category"""

# Aggregate marketing_spend and profit by product_category
# If we want to see the relationship over time, we would aggregate by month and product category
# For a general relationship, we can sum these per category.

agg_data_mp = df.groupby('product_category')[['marketing_spend', 'profit']].sum().reset_index()

plt.figure(figsize=(12, 7))
sns.scatterplot(x='marketing_spend', y='profit', hue='product_category', data=df, palette='Dark2', alpha=0.6, s=100) # Using raw data for more points

# Add trend lines for each product category
for category in df['product_category'].unique():
    subset = df[df['product_category'] == category]
    sns.regplot(x='marketing_spend', y='profit', data=subset, scatter=False, color=COLORS.get(category, 'gray'), ci=None, line_kws={'linestyle':'--'}) # Using COLORS from before

plt.title('Marketing Spend vs. Profit by Product Category', fontsize=16, color=NAVY)
plt.xlabel('Total Marketing Spend ($)', fontsize=12, color=NAVY)
plt.ylabel('Total Profit ($)', fontsize=12, color=NAVY)
plt.grid(True, linestyle='--', alpha=0.6)
plt.gca().xaxis.set_major_formatter(mtick.FormatStrFormatter('$%.0f'))
plt.gca().yaxis.set_major_formatter(mtick.FormatStrFormatter('$%.0f'))
plt.legend(title='Product Category', bbox_to_anchor=(1.05, 1), loc='upper left')
plt.tight_layout()
plt.show()

"""# OPERATIONS TEAM CHARTS

**return rate by region / product**


*   bar chart
*   y-axis = return rate
*   x-axis = region / product (filter)

**profit per unit (by product category)**


*   bar chart
*   formula: profit /(divided by) units sold

**customer satisfaction vs return rate**


*   scatter plot
*   x-axis = customer satisfaction
*   y-axis = return rate

**marketing spend vs profit (by product category)**


*   scatter plot
*   x-axis = marketing spend
*   y-axis = profit
*   color code each category
*   add a trend line for each product category
"""